"""
agents/predictor.py — Phase 4 predictive anomaly detection and trend forecasting.

Queries the Phase 3 history DB for recurring metric signals, then asks Claude
to forecast whether any resource is trending toward a breach before it happens.

Three types of predictions:
  1. Recurrence forecast    — "this issue has appeared 4x in 30 days, expect it again"
  2. Escalation forecast    — "severity has been creeping up: low→medium→high over 3 runs"
  3. Pattern-based forecast — "every Monday this firewall finding reappears"

Output is a list of PredictiveFinding objects, which are surfaced in the
executive summary before the reactive findings from the observe cycle.

Usage:
    predictor = Predictor()
    predictions = predictor.run()   # list[PredictiveFinding]
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime, timezone

import anthropic

from config import ANTHROPIC_API_KEY, SUPERVISOR_MODEL, PREDICTOR_LOOKBACK_RUNS
from memory.history import history_db


@dataclass
class PredictiveFinding:
    """A proactive, forward-looking finding generated by the Predictor."""
    resource: str
    check_type: str
    agent: str
    prediction: str           # human-readable forecast
    confidence: str           # "high" | "medium" | "low"
    recommended_action: str   # what to do proactively
    occurrences: int
    last_seen: str
    predicted_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    def to_dict(self) -> dict:
        return self.__dict__.copy()


class Predictor:
    """
    Analyses historical finding patterns and forecasts future issues.
    Uses Claude Opus for reasoning over trend data.
    """

    def __init__(self):
        self._client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

    def run(self) -> list[PredictiveFinding]:
        """
        Run the full prediction cycle.
        Returns a (possibly empty) list of PredictiveFinding objects.
        """
        patterns = history_db.recurring_findings()
        escalations = self._detect_escalations()

        if not patterns and not escalations:
            return []

        return self._forecast(patterns, escalations)

    # ── Internal ───────────────────────────────────────────────────────────────

    def _detect_escalations(self) -> list[dict]:
        """
        Find resources where severity has been worsening across recent runs.
        Queries the raw findings table and looks for low→medium→high sequences.
        """
        import sqlite3
        from pathlib import Path
        from config import HISTORY_DB

        db_path = Path(HISTORY_DB)
        if not db_path.exists():
            return []

        try:
            conn = sqlite3.connect(str(db_path))
            conn.row_factory = sqlite3.Row
            rows = conn.execute(
                """
                SELECT resource, check_type, agent,
                       GROUP_CONCAT(severity ORDER BY recorded_at ASC) AS severity_trend,
                       COUNT(*) AS cnt,
                       MAX(recorded_at) AS last_seen
                FROM findings
                GROUP BY resource, check_type
                HAVING cnt >= 3
                ORDER BY last_seen DESC
                LIMIT 50
                """
            ).fetchall()
            conn.close()
        except Exception:
            return []

        escalations = []
        _severity_rank = {"info": 0, "low": 1, "medium": 2, "high": 3, "critical": 4}
        for row in rows:
            trend = (row["severity_trend"] or "").split(",")
            ranks = [_severity_rank.get(s.strip(), 0) for s in trend[-5:]]  # last 5
            if len(ranks) >= 3 and ranks[-1] > ranks[0]:
                escalations.append({
                    "resource": row["resource"],
                    "check_type": row["check_type"],
                    "agent": row["agent"],
                    "severity_trend": trend[-5:],
                    "occurrences": row["cnt"],
                    "last_seen": row["last_seen"],
                })
        return escalations

    def _forecast(
        self,
        patterns: list[dict],
        escalations: list[dict],
    ) -> list[PredictiveFinding]:
        """Ask Claude to reason over patterns and escalations, return predictions."""
        if not patterns and not escalations:
            return []

        prompt_data = {
            "recurring_patterns": patterns[:20],
            "escalating_severity": escalations[:10],
            "lookback_runs": PREDICTOR_LOOKBACK_RUNS,
        }

        system = """You are a predictive cloud operations analyst.
You receive historical finding patterns from a GCP monitoring system.
Your job is to forecast future problems BEFORE they become incidents.

For each pattern or escalation, decide:
1. Is this likely to recur or worsen soon?
2. What is your confidence? (high/medium/low)
3. What proactive action should the engineer take NOW?

Return ONLY a JSON array. Each item:
{
  "resource": "resource name",
  "check_type": "check type string",
  "agent": "agent domain",
  "prediction": "plain English forecast (1-2 sentences)",
  "confidence": "high|medium|low",
  "recommended_action": "specific proactive step",
  "occurrences": <int>,
  "last_seen": "ISO timestamp"
}

Only include items where you are at least medium-confidence something will happen.
If nothing is predictable, return: []
"""

        response = self._client.messages.create(
            model=SUPERVISOR_MODEL,
            max_tokens=2048,
            thinking={"type": "adaptive"},
            system=system,
            messages=[{"role": "user", "content": json.dumps(prompt_data, indent=2, default=str)}],
        )

        raw = next((b.text for b in response.content if b.type == "text"), "[]")

        # Strip markdown fences if present
        text = raw.strip()
        if text.startswith("```"):
            text = text.split("```")[1]
            if text.startswith("json"):
                text = text[4:]
        text = text.strip()

        try:
            items = json.loads(text)
        except json.JSONDecodeError:
            return []

        results = []
        for item in items:
            try:
                results.append(PredictiveFinding(
                    resource=item.get("resource", ""),
                    check_type=item.get("check_type", ""),
                    agent=item.get("agent", ""),
                    prediction=item.get("prediction", ""),
                    confidence=item.get("confidence", "low"),
                    recommended_action=item.get("recommended_action", ""),
                    occurrences=int(item.get("occurrences", 0)),
                    last_seen=item.get("last_seen", ""),
                ))
            except Exception:
                continue

        return results
