"""
tools/scaffolder.py — Generates stub tool modules for unmonitored GCP services.

Usage:
    python main.py --scaffold cloudfunctions.googleapis.com
    python main.py --scaffold cloudfunctions.googleapis.com --domain deployment

The generated file is placed in tools/gcp/ and is immediately discovered
by the registry on the next run. You only need to fill in the tool functions.
"""
from __future__ import annotations

import re
from pathlib import Path


# ── Domain hints ──────────────────────────────────────────────────────────────
# Best-guess domain for common GCP APIs. Used when --domain is not specified.

API_DOMAIN_HINTS: dict[str, str] = {
    # Deployment / CI-CD
    "cloudfunctions.googleapis.com":       "deployment",
    "appengine.googleapis.com":            "deployment",
    "cloudscheduler.googleapis.com":       "deployment",
    "cloudtasks.googleapis.com":           "deployment",
    "artifactregistry.googleapis.com":     "deployment",
    "clouddeploy.googleapis.com":          "deployment",
    "cloudbuild.googleapis.com":           "deployment",
    "run.googleapis.com":                  "deployment",
    # Infrastructure / databases
    "spanner.googleapis.com":              "infra",
    "bigtable.googleapis.com":             "infra",
    "redis.googleapis.com":                "infra",
    "filestore.googleapis.com":            "infra",
    "dns.googleapis.com":                  "infra",
    "container.googleapis.com":            "infra",
    "sqladmin.googleapis.com":             "infra",
    "vpcaccess.googleapis.com":            "infra",
    "networkmanagement.googleapis.com":    "infra",
    # Security
    "secretmanager.googleapis.com":        "security",
    "cloudkms.googleapis.com":             "security",
    "containeranalysis.googleapis.com":    "security",
    "binaryauthorization.googleapis.com":  "security",
    "iam.googleapis.com":                  "security",
    "iap.googleapis.com":                  "security",
    # Data / analytics
    "composer.googleapis.com":             "data",
    "dataflow.googleapis.com":             "data",
    "datacatalog.googleapis.com":          "data",
    "aiplatform.googleapis.com":           "data",
    "vertexai.googleapis.com":             "data",
    "datafusion.googleapis.com":           "data",
    "datastream.googleapis.com":           "data",
    # Cost / billing
    "billingbudgets.googleapis.com":       "cost",
    "recommender.googleapis.com":          "cost",
    # Incident / monitoring
    "cloudtrace.googleapis.com":           "incident",
    "clouderrorreporting.googleapis.com":  "incident",
    "cloudprofiler.googleapis.com":        "incident",
}

# ── Helpers ───────────────────────────────────────────────────────────────────

def _api_to_module_name(api: str) -> str:
    """
    Convert an API identifier to a Python module filename.
    e.g. 'cloudfunctions.googleapis.com' → 'cloudfunctions'
         'bigquery-json.googleapis.com'   → 'bigquery_json'
    """
    name = api.replace(".googleapis.com", "").replace("-", "_")
    return re.sub(r"[^a-z0-9_]", "_", name.lower())


def _api_to_display_name(api: str) -> str:
    """
    Make a human-readable display name from the API identifier.
    e.g. 'cloudfunctions.googleapis.com' → 'Cloud Functions'
    """
    raw = api.replace(".googleapis.com", "").replace("-", " ")
    # Insert spaces before capital letters (for camelCase APIs)
    spaced = re.sub(r"([a-z])([A-Z])", r"\1 \2", raw)
    return spaced.title()


def _suggest_domain(api: str) -> str:
    """Return the suggested agent domain for a given API, or 'infra' as fallback."""
    return API_DOMAIN_HINTS.get(api, "infra")


# ── Scaffold generator ────────────────────────────────────────────────────────

def generate_stub(api: str, domain: str | None = None) -> Path:
    """
    Generate a stub tools/gcp/<module>.py for the given API.

    Args:
        api:    GCP API identifier, e.g. 'cloudfunctions.googleapis.com'
        domain: Agent domain override. If None, inferred from API_DOMAIN_HINTS.

    Returns:
        Path to the generated file.

    Raises:
        FileExistsError: if the module file already exists.
    """
    module_name = _api_to_module_name(api)
    domain = domain or _suggest_domain(api)
    display_name = _api_to_display_name(api)

    output_path = Path(__file__).parent / "gcp" / f"{module_name}.py"
    if output_path.exists():
        raise FileExistsError(
            f"{output_path} already exists. Edit it directly or delete it first."
        )

    # Derive a plausible resource name for placeholder function
    resource = module_name.rstrip("s")  # naive singularize

    stub = f'''"""GCP {display_name} — read-only data collection.

Generated by: python main.py --scaffold {api}

TODO:
  1. Replace list_{resource}s() with real API calls.
  2. Find the correct API name/version at:
         https://developers.google.com/discovery/v1/reference/apis/list
  3. Run `python main.py --list-services` to confirm this module is detected.
  4. Run `python main.py --agent {domain}` to test it end-to-end.
"""
from __future__ import annotations
from typing import Any
from config import GOOGLE_CLOUD_PROJECT

PROJECT = GOOGLE_CLOUD_PROJECT


def list_{resource}s() -> list[dict[str, Any]]:
    """TODO: List {display_name} resources in the project."""
    try:
        from googleapiclient import discovery
        import google.auth
        credentials, _ = google.auth.default()

        # TODO: Replace "<api_name>" and "<version>" with the correct values.
        # Hint: search https://developers.google.com/discovery/v1/reference/apis/list
        service = discovery.build("<api_name>", "<version>", credentials=credentials)

        # TODO: Replace with the correct list call for this API.
        result = service.projects().<resources>().list(
            parent=f"projects/{{PROJECT}}"
        ).execute()

        return [
            {{
                "name": item.get("name", "").split("/")[-1],
                # TODO: Add more fields relevant to this resource.
            }}
            for item in result.get("<resources>", [])
        ]
    except Exception as e:
        return [{{"error": str(e)}}]


DESCRIPTOR = {{
    "api": "{api}",
    "display_name": "{display_name}",
    "domains": ["{domain}"],
    "tools": [list_{resource}s],
}}
'''

    output_path.write_text(stub)
    return output_path


# ── Coverage report ───────────────────────────────────────────────────────────

def coverage_report() -> dict:
    """
    Return a structured coverage report comparing enabled APIs vs registered modules.
    Used by main.py to print the startup warning.
    """
    from tools.registry import get_unmonitored_apis, list_all_services

    unmonitored = get_unmonitored_apis()
    all_services = list_all_services()
    monitored = [s for s in all_services if s["enabled"]]

    gaps = []
    for api in unmonitored:
        gaps.append({
            "api": api,
            "suggested_domain": _suggest_domain(api),
            "scaffold_cmd": f"python main.py --scaffold {api}",
        })

    return {
        "monitored_count": len(monitored),
        "gap_count": len(gaps),
        "gaps": gaps,
    }
